### ISSUE TITLE
Check for NPE when reconciliation starts during an ongoing cluster deletion operation

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#171]
When the cluster ConfigMap is deleted in order to delete the entire cluster, before starting the delete operation it's needed to stop the timer for the reconcile. It could happen that while deleting the reconcile jump in and some resources are already gone (I got some `NullPointerException`)

**Comment by scholzj** [comment]
I'm not sure stopping the reconcile timer is the best thing to do. Isn't it better to check for the NPEs? The locking mechanism should make sure that there are no delete operations running in parallel for the same resource, so I would expect that it should not be that complicated to prevent the NPE.

While writing the prototype I was considering to have some mechanism to say that with given resource is something happening at the moment. But then it seemed unnecessary, so I removed it (well, it was never complete in the first place).

**Comment by ppatierno** [comment]
Agree with you that checking for NPE is important but what the reason of having the timer still running while I'm deleting the cluster ? Maybe it's just because the cluster-controller could handle more than one cluster and the reconciliation is needed of the others ?

**Comment by scholzj** [comment]
Exactly ... the controller is not per cluster ... so you would stop reconciliation for other clusters.

**Comment by tombentley** [comment]
FWIW, there's a similar situation in the topic-controller. There I created a dedicated class (`Inflight`) which tracks reconciliations on a per-topic basis (it's complicated by the fact that each reconciliation involves lots of vertx calls, and we're interested in the overall reconciliation). But `Inflight` lets you queue another reconciliation for when the current one has finished, or runs the reconciliation immediately if there is no current one. (It's still not perfect as `Inflight` uses a `ConcurrentHashMap`, so strictly speaking it will block a write when two writers are competing over the same topic, but in practice that's almost never.)

**Comment by ppatierno** [comment]
I reproduced it with following log : 

2018-02-27 09:46:46 INFO  ClusterController:145 - Deleted ConfigMap my-cluster in namespace myproject
2018-02-27 09:46:46 INFO  AbstractClusterOperations:209 - Deleting Kafka cluster my-cluster in namespace myproject
2018-02-27 09:46:46 INFO  AbstractClusterOperations:151 - delete topic-controller cluster my-cluster-topic-controller in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:98 - Deleting Deployment my-cluster-topic-controller in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:100 - Deployment my-cluster-topic-controller in namespace myproject has been deleted
2018-02-27 09:46:46 INFO  AbstractClusterOperations:162 - topic-controller cluster my-cluster-topic-controller in namespace myproject: successful delete
2018-02-27 09:46:46 INFO  AbstractClusterOperations:151 - delete kafka cluster my-cluster-kafka in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:98 - Deleting ConfigMap my-cluster-kafka-metrics-config in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:98 - Deleting Service my-cluster-kafka-headless in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:98 - Deleting Service my-cluster-kafka in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:98 - Deleting StatefulSet my-cluster-kafka in namespace myproject
2018-02-27 09:46:46 INFO  AbstractOperations:100 - ConfigMap my-cluster-kafka-metrics-config in namespace myproject has been deleted
2018-02-27 09:46:46 INFO  AbstractOperations:100 - Service my-cluster-kafka-headless in namespace myproject has been deleted
2018-02-27 09:46:47 INFO  AbstractOperations:100 - Service my-cluster-kafka in namespace myproject has been deleted
2018-02-27 09:46:47 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
2018-02-27 09:46:47 INFO  AbstractClusterOperations:280 - Reconciling Kafka clusters ...
2018-02-27 09:46:47 INFO  AbstractClusterOperations:325 - Reconciliation: Kafka cluster my-cluster-kafka should be deleted
2018-02-27 09:46:47 INFO  AbstractClusterOperations:209 - Deleting Kafka cluster my-cluster in namespace myproject
2018-02-27 09:46:47 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect clusters ...
2018-02-27 09:46:47 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect S2I clusters ...
2018-02-27 09:46:52 INFO  AbstractOperations:100 - StatefulSet my-cluster-kafka in namespace myproject has been deleted
2018-02-27 09:46:52 INFO  AbstractClusterOperations:162 - kafka cluster my-cluster-kafka in namespace myproject: successful delete
2018-02-27 09:46:52 ERROR AbstractClusterOperations:153 - Error while getting required kafka cluster state for delete operation
java.lang.NullPointerException
	at io.strimzi.controller.cluster.resources.KafkaCluster.fromStatefulSet(KafkaCluster.java:157)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations$4.getCluster(KafkaClusterOperations.java:248)
	at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$execute$1(AbstractClusterOperations.java:150)
	at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
2018-02-27 09:46:52 INFO  AbstractClusterOperations:151 - delete zookeeper cluster my-cluster-zookeeper in namespace myproject
2018-02-27 09:46:52 ERROR AbstractClusterOperations:214 - Failed to delete Kafka cluster my-cluster in namespace myproject
2018-02-27 09:46:52 INFO  AbstractOperations:98 - Deleting ConfigMap my-cluster-zookeeper-metrics-config in namespace myproject
2018-02-27 09:46:52 INFO  AbstractOperations:98 - Deleting Service my-cluster-zookeeper in namespace myproject
2018-02-27 09:46:52 INFO  AbstractOperations:98 - Deleting Service my-cluster-zookeeper-headless in namespace myproject
2018-02-27 09:46:52 INFO  AbstractOperations:98 - Deleting StatefulSet my-cluster-zookeeper in namespace myproject
2018-02-27 09:46:52 INFO  AbstractOperations:100 - ConfigMap my-cluster-zookeeper-metrics-config in namespace myproject has been deleted
2018-02-27 09:46:52 INFO  AbstractOperations:100 - Service my-cluster-zookeeper-headless in namespace myproject has been deleted
2018-02-27 09:46:52 INFO  AbstractOperations:100 - Service my-cluster-zookeeper in namespace myproject has been deleted
2018-02-27 09:46:52 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
2018-02-27 09:46:52 INFO  AbstractClusterOperations:280 - Reconciling Kafka clusters ...
2018-02-27 09:46:52 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect clusters ...
2018-02-27 09:46:52 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect S2I clusters ...
2018-02-27 09:46:53 INFO  AbstractOperations:100 - StatefulSet my-cluster-zookeeper in namespace myproject has been deleted
2018-02-27 09:46:53 INFO  AbstractClusterOperations:162 - zookeeper cluster my-cluster-zookeeper in namespace myproject: successful delete
2018-02-27 09:46:53 INFO  AbstractClusterOperations:212 - Kafka cluster deleted my-cluster in namespace myproject
2018-02-27 09:46:57 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
2018-02-27 09:46:57 INFO  AbstractClusterOperations:280 - Reconciling Kafka clusters ...
2018-02-27 09:46:57 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect clusters ...
2018-02-27 09:46:57 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect S2I clusters ...
2018-02-27 09:47:02 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
2018-02-27 09:47:02 INFO  AbstractClusterOperations:280 - Reconciling Kafka clusters ...
2018-02-27 09:47:02 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect clusters ...
2018-02-27 09:47:02 INFO  AbstractClusterOperations:280 - Reconciling Kafka Connect S2I clusters ...

**Comment by ppatierno** [comment]
closed by #263
