### ISSUE TITLE
NPE on topic-controller restart after changing topic partitions number

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi#192]
So following the steps for reproducing the error ...

- Start the topic controller and create a new topic ConfigMap describing a topic with just 1 partition. All works fine and ConfigMap, Kafka and Strimzi Zk store are aligned

- Use the `kafka-topics.sh` tool for altering the topic increasing the number of partitions, i.e. : 

`bin/kafka-topics.sh --zookeeper 172.30.29.40:2181 --alter --topic orders --partitions 2`

Of course the ConfigMap and the Strimzi Zk store aren't updated yet (working on the issue #137).

- Stop topic controller.

- Start topic controller, the following exception is thrown : 

[2018-01-25 10:23:58,429] INFO  <Controller  :402> [oop-thread-5] Reconciling topic orders, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-01-25 10:23:58,430] DEBUG <Controller  :467> [oop-thread-5] 3 way diff
[2018-01-25 10:23:58,431] DEBUG <Controller  :529> [oop-thread-5] topicStore->kafkaTopic: TopicDiff{differences={numPartitions=newNumPartitions=2}}
[2018-01-25 10:23:58,432] DEBUG <Controller  :531> [oop-thread-5] topicStore->k8sTopic: TopicDiff{differences={}}
[2018-01-25 10:23:58,432] DEBUG <Controller  :540> [oop-thread-5] Diffs do not conflict, merged diff: TopicDiff{differences={numPartitions=newNumPartitions=2}}
[2018-01-25 10:23:58,432] DEBUG <Controller  :562> [oop-thread-5] Updating cm, kafka topic and topicStore
[2018-01-25 10:23:58,436] DEBUG <Controller  :586> [oop-thread-5] Enqueuing event UpdateConfigMap(topicName=orders)
[2018-01-25 10:23:58,574] INFO  <igMapWatcher:48> [0.1:8443/...] ConfigMap watch received event MODIFIED on map orders with labels {strimzi.io/kind=topic}
[2018-01-25 10:23:58,577] DEBUG <InFlight    :119> [0.1:8443/...] resultHandler:io.strimzi.controller.topic.ConfigMapWatcher$$Lambda$24/1911605950@56feb51d, action:onConfigMapModified-1648139407, fut:onConfigMapModified-1648139407
[2018-01-25 10:23:58,577] DEBUG <Controller  :586> [oop-thread-5] Enqueuing event io.strimzi.controller.topic.Controller$$Lambda$62/696409212@7263b06d
[2018-01-25 10:23:58,577] DEBUG <InFlight    :126> [0.1:8443/...] Queueing onConfigMapModified-1648139407 for deferred execution after onConfigMapAdded-1125582984
[2018-01-25 10:23:58,578] DEBUG <Controller  :586> [oop-thread-5] Enqueuing event UpdateKafkaPartitions(topicName=orders)
[2018-01-25 10:23:58,580] DEBUG <aAdminClient:189> [oop-thread-5] [AdminClient clientId=adminclient-1] Queueing Call(callName=createPartitions, deadlineMs=1516872358579) with a timeout 120000 ms from now.
Jan 25, 2018 10:23:58 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
	at io.strimzi.controller.topic.BaseKafkaImpl$UniWork.<init>(BaseKafkaImpl.java:88)
	at io.strimzi.controller.topic.ControllerAssignedKafkaImpl.increasePartitions(ControllerAssignedKafkaImpl.java:73)
	at io.strimzi.controller.topic.Controller$IncreaseKafkaPartitions.handle(Controller.java:267)
	at io.strimzi.controller.topic.Controller$IncreaseKafkaPartitions.handle(Controller.java:252)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

After this exception, the ConfigMap is updated to 2 partitions but not the Strimzi Zk store which still says 1 partition.
Deleting the ConfigMap isn't reflected in a corresponding deletion of the topic in Kafka and in the Strimzi Zk store.

**Comment by ppatierno** [comment]
Fixed by 8c5f267a9b9f90994bcde24b549c1f0f49e236f5
