### ISSUE TITLE
IllegalStateException during config map deletion

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi#256]
### Step to reproduce:
1. Clone and open Strimzi sources https://github.com/strimzi/strimzi
2. Up cluster
`$ oc clucter up`
3. Login as admin
`$ oc login -u system:admin`
4. Deploy Cluster Controller
`$ oc create -f resources/openshift/cluster-controller-with-template.yaml`
5. Deploy Topic Controller
`$ oc create -f resources/openshift/topic-controller-with-template.yaml`
6. Login to OpenShift https://127.0.0.1:8443
7. Create **"Apache Kafka (Ephemeral storage)"**
7.1 Click "Add to project"
7.2 Click "Select from project"
7.3 Select "Apache Kafka (Ephemeral storage)" and click "Next"
7.4 Use default configurations:
_Number of Zookeper cluster nodes: 1
Number of Kafka cluster nodes: 3_
7.5 Click "Create" and wait for the message "Apache Kafka (Ephemeral storage) has been created"
7.6 Open page "Pods" and wait when all pods will have status "Running"
8. Create **"Strimzi Topic Controller"**
8.1 Click "Add to project"
8.2 Click "Select from project"
8.3 Select "Strimzi Topic Controller" and click "Next"
8.4 Use default configurations
8.5 Click "Create" and wait for the message "Success Strimzi Topic Controller has been created."
8.6 Open page "Pods" and wait when all pods will have status "Running"
9. Remove config map for cluster
9.1 Open "Config Maps" page and open config map for your cluster
9.2 Click "Actions"
9.3 click "Delete" in dropdown list and wait for message "Config map 'my-cluster' was marked for deletion"
10. Open logs for pod **"strimzi-cluster-controller"**
10.1 Open page "Pods"
10.2 Open pod **"strimzi-cluster-controller"**
10.3 Select tab "Logs"

### Actual result:
Log has exception: `java.lang.IllegalStateException: ConfigMap my-cluster doesn't exist anymore in namespace myproject`

### Additional information:
Openshift - v3.7.1+a8deba5-34
Strimzi - 141 build
All log file will be attached to Jira issue

Log:

```
2018-02-26 19:16:08 INFO  AbstractClusterOperations:162 - kafka cluster my-cluster-kafka in namespace myproject: successful delete
--
  | 2018-02-26 19:16:08 INFO  AbstractClusterOperations:151 - delete zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-02-26 19:16:08 INFO  AbstractOperations:98 - Deleting Service my-cluster-zookeeper in namespace myproject
  | 2018-02-26 19:16:08 INFO  AbstractOperations:98 - Deleting Service my-cluster-zookeeper-headless in namespace myproject
  | 2018-02-26 19:16:08 INFO  AbstractOperations:98 - Deleting ConfigMap my-cluster-zookeeper-metrics-config in namespace myproject
  | 2018-02-26 19:16:08 ERROR AbstractClusterOperations:153 - Error while getting required kafka cluster state for update operation
  | java.lang.IllegalStateException: ConfigMap my-cluster doesn't exist anymore in namespace myproject
  | at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations$5.getCluster(KafkaClusterOperations.java:277)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$execute$1(AbstractClusterOperations.java:150)
  | at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  | at java.lang.Thread.run(Thread.java:748)
  | 2018-02-26 19:16:08 ERROR AbstractClusterOperations:235 - Failed to update Kafka cluster my-cluster.
  | 2018-02-26 19:16:08 INFO  AbstractOperations:100 - Service my-cluster-zookeeper in namespace myproject has been deleted
  | 2018-02-26 19:16:08 INFO  AbstractOperations:100 - Service my-cluster-zookeeper-headless in namespace myproject has been deleted
  | 2018-02-26 19:16:08 INFO  AbstractOperations:100 - ConfigMap my-cluster-zookeeper-metrics-config in namespace myproject has been deleted
  | 2018-02-26 19:16:08 INFO  AbstractOperations:98 - Deleting StatefulSet my-cluster-zookeeper in namespace myproject
  | 2018-02-26 19:16:10 INFO  ClusterController:86 - Triggering periodic reconciliation for namespace myproject...
```

**Comment by serrss** [comment]
This bug was fixed with https://github.com/strimzi/strimzi/issues/171
Checked build - https://travis-ci.org/strimzi/strimzi/builds/349229157
