### ISSUE TITLE
EntityExistsException during Kafka Connect creation

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi#258]
### Step to reproduce:
1. Clone and open Strimzi sources https://github.com/strimzi/strimzi
2. Up cluster
`$ oc clucter up`
3. Login as admin
`$ oc login -u system:admin`
4. Deploy Cluster Controller
`$ oc create -f resources/openshift/cluster-controller-with-template.yaml`
5. Deploy Topic Controller
`$ oc create -f resources/openshift/topic-controller-with-template.yaml`
6. Login to OpenShift https://127.0.0.1:8443
7. Create **"Apache Kafka (Persistent storage)"**
7.1 Click "Add to project"
7.2 Click "Select from project"
7.3 Select "Apache Kafka (Persistent storage)" and click "Next"
7.4 Use default configurations:
_Number of Zookeper cluster nodes: 3
Number of Kafka cluster nodes: 3_
7.5 Click "Create" and wait for the message "Apache Kafka (Persistent storage) has been created"
7.6 Open page "Pods" and wait when all pods will have status "Running"
8. Create **"Strimzi Topic Controller"**
8.1 Click "Add to project"
8.2 Click "Select from project"
8.3 Select "Strimzi Topic Controller" and click "Next"
8.4 Use default configurations
8.5 Click "Create" and wait for the message "Success Strimzi Topic Controller has been created."
8.6 Open page "Pods" and wait when all pods will have status "Running"
9. Create **"Apache Kafka Connect"**
9.1 Click "Add to project"
9.2 Click "Select from project"
9.3 Select "Apache Kafka Connect" and click "Next"
9.4 Use default configurations
9.5 Click "Create" and wait for the message "Apache Kafka Connect has been created."
9.6 Open page "Pods" and wait when all pods will have status "Running"
10. Open logs for _strimzi-topic-controller_ and wait 5 mins

### Actual result:
Log has `[2018-02-25 20:31:57,589] ERROR <igMapWatcher:47> [oop-thread-0] Failure processing ConfigMap watch event ADDED on map connect-cluster-offsets with labels {strimzi.io/kind=topic}: null
io.strimzi.controller.topic.TopicStore$EntityExistsException
`
### Additional information:
Openshift - v3.7.1+a8deba5-34
Strimzi - 141 build
All log file will be attached to Jira issue

### Topic controller log: 
```
[2018-02-25 20:17:52,172] INFO  <igMapWatcher:38> [oop-thread-0] Success processing ConfigMap watch event ADDED on map connect-cluster-configs with labels {strimzi.io/kind=topic}
[2018-02-25 20:31:57,378] INFO  <Session     :158> [oop-thread-0] Starting periodic reconciliation
[2018-02-25 20:31:57,540] INFO  <Controller  :384> [oop-thread-0] Reconciling topic connect-cluster-configs, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-02-25 20:31:57,546] INFO  <Controller  :524> [oop-thread-0] All three topics are identical
[2018-02-25 20:31:57,547] INFO  <Controller  :384> [oop-thread-0] Reconciling topic connect-cluster-status, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-02-25 20:31:57,547] INFO  <Controller  :524> [oop-thread-0] All three topics are identical
[2018-02-25 20:31:57,550] INFO  <Controller  :384> [oop-thread-0] Reconciling topic connect-cluster-offsets, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2018-02-25 20:31:57,572] INFO  <igMapWatcher:35> [ault.svc/...] ConfigMap watch received event ADDED on map connect-cluster-offsets with labels {strimzi.io/kind=topic}
[2018-02-25 20:31:57,586] INFO  <Controller  :384> [oop-thread-5] Reconciling topic connect-cluster-offsets, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:null
[2018-02-25 20:31:57,589] ERROR <igMapWatcher:47> [oop-thread-0] Failure processing ConfigMap watch event ADDED on map connect-cluster-offsets with labels {strimzi.io/kind=topic}: null
io.strimzi.controller.topic.TopicStore$EntityExistsException
	at io.strimzi.controller.topic.ZkTopicStore.lambda$create$2(ZkTopicStore.java:82)
	at io.strimzi.controller.topic.zk.ZkImpl.lambda$invokeOnContext$1(ZkImpl.java:124)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
[2018-02-25 20:31:57,596] WARN  <Controller  :89> [oop-thread-0] io.strimzi.controller.topic.TopicStore$EntityExistsException
[2018-02-25 20:31:57,601] WARN  <Controller  :89> [oop-thread-0] Failure processing ConfigMap watch event ADDED on map connect-cluster-offsets with labels {strimzi.io/kind=topic}: null
[2018-02-25 20:46:57,377] INFO  <Session     :158> [oop-thread-0] Starting periodic reconciliation
```

**Comment by serrss** [comment]
@ppatierno Issue was fixed!
