### ISSUE TITLE
Null pointer exception when deleting cluster

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#303]
We still seem to have some NPEs:

```
2018-03-07 22:53:00 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
--
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:251 - Reconciliation: Kafka cluster my-cluster should be checked for updates
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:252 - Checking for updates in Kafka cluster my-cluster
  | 2018-03-07 22:53:00 INFO  KafkaClusterOperations:615 - Updating Zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:150 - update zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:160 - zookeeper cluster my-cluster-zookeeper in namespace myproject: successful update
  | 2018-03-07 22:53:00 INFO  KafkaClusterOperations:436 - Updating Kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:150 - update kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:160 - kafka cluster my-cluster-kafka in namespace myproject: successful update
  | 2018-03-07 22:53:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:53:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:150 - update topic-controller cluster my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:160 - topic-controller cluster my-cluster-topic-controller in namespace myproject: successful update
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:255 - Kafka cluster updated my-cluster
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:239 - Reconciling Kafka Connect S2I clusters ...
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:251 - Reconciliation: Kafka Connect S2I cluster my-connect-cluster should be checked for updates
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:252 - Checking for updates in Kafka Connect S2I cluster my-connect-cluster
  | 2018-03-07 22:53:00 INFO  KafkaConnectS2IClusterOperations:192 - Updating Kafka Connect S2I cluster my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:150 - kafka-connect-s2i update cluster my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:160 - update cluster my-connect-cluster-connect in namespace myproject: successful kafka-connect-s2i
  | 2018-03-07 22:53:00 INFO  AbstractClusterOperations:255 - Kafka Connect S2I cluster updated my-connect-cluster
  | 2018-03-07 22:53:42 INFO  ClusterController:148 - ConfigMap my-connect-cluster in namespace myproject was MODIFIED
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:239 - Reconciling Kafka Connect S2I clusters ...
  | 2018-03-07 22:53:42 INFO  ClusterController:148 - ConfigMap my-connect-cluster in namespace myproject was DELETED
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:251 - Reconciliation: Kafka Connect S2I cluster my-connect-cluster should be checked for updates
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:252 - Checking for updates in Kafka Connect S2I cluster my-connect-cluster
  | 2018-03-07 22:53:42 ERROR AbstractClusterOperations:152 - Error while getting required update cluster state for kafka-connect-s2i operation
  | java.lang.IllegalStateException: ConfigMap my-connect-cluster doesn't exist anymore in namespace myproject
  | at io.strimzi.controller.cluster.operations.cluster.KafkaConnectS2IClusterOperations$3.getCluster(KafkaConnectS2IClusterOperations.java:199)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.execute(AbstractClusterOperations.java:149)
  | at io.strimzi.controller.cluster.operations.cluster.KafkaConnectS2IClusterOperations.update(KafkaConnectS2IClusterOperations.java:149)
  | at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$reconcile$5(AbstractClusterOperations.java:253)
  | at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  | at java.lang.Thread.run(Thread.java:748)
  | 2018-03-07 22:53:42 ERROR AbstractClusterOperations:257 - Failed to update Kafka Connect S2I cluster my-connect-cluster.
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:239 - Reconciling Kafka Connect S2I clusters ...
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:279 - Reconciliation: Kafka Connect S2I cluster my-connect-cluster-connect should be deleted
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:281 - Deleting Kafka Connect S2I cluster my-connect-cluster in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractClusterOperations:150 - delete kafka-connect-s2i cluster my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:99 - Deleting Service my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:99 - Deleting BuildConfig my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:101 - Service my-connect-cluster-connect in namespace myproject has been deleted
  | 2018-03-07 22:53:42 INFO  AbstractOperations:99 - Deleting DeploymentConfig my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:99 - Deleting ImageStream my-connect-cluster-connect-source in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:99 - Deleting ImageStream my-connect-cluster-connect in namespace myproject
  | 2018-03-07 22:53:42 INFO  AbstractOperations:101 - ImageStream my-connect-cluster-connect-source in namespace myproject has been deleted
  | 2018-03-07 22:53:42 INFO  AbstractOperations:101 - ImageStream my-connect-cluster-connect in namespace myproject has been deleted
  | 2018-03-07 22:53:42 INFO  AbstractOperations:101 - BuildConfig my-connect-cluster-connect in namespace myproject has been deleted
  | 2018-03-07 22:53:43 INFO  AbstractOperations:101 - DeploymentConfig my-connect-cluster-connect in namespace myproject has been deleted
  | 2018-03-07 22:53:43 INFO  AbstractClusterOperations:160 - kafka-connect-s2i cluster my-connect-cluster-connect in namespace myproject: successful delete
  | 2018-03-07 22:53:43 INFO  AbstractClusterOperations:287 - Kafka Connect S2I cluster deleted my-connect-cluster in namespace myproject
  | 2018-03-07 22:55:00 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:251 - Reconciliation: Kafka cluster my-cluster should be checked for updates
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:252 - Checking for updates in Kafka cluster my-cluster
  | 2018-03-07 22:55:00 INFO  KafkaClusterOperations:615 - Updating Zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:150 - update zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:160 - zookeeper cluster my-cluster-zookeeper in namespace myproject: successful update
  | 2018-03-07 22:55:00 INFO  KafkaClusterOperations:436 - Updating Kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:150 - update kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:160 - kafka cluster my-cluster-kafka in namespace myproject: successful update
  | 2018-03-07 22:55:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:55:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:150 - update topic-controller cluster my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:160 - topic-controller cluster my-cluster-topic-controller in namespace myproject: successful update
  | 2018-03-07 22:55:00 INFO  AbstractClusterOperations:255 - Kafka cluster updated my-cluster
  | 2018-03-07 22:57:00 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace myproject...
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:251 - Reconciliation: Kafka cluster my-cluster should be checked for updates
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:252 - Checking for updates in Kafka cluster my-cluster
  | 2018-03-07 22:57:00 INFO  KafkaClusterOperations:615 - Updating Zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:150 - update zookeeper cluster my-cluster-zookeeper in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:160 - zookeeper cluster my-cluster-zookeeper in namespace myproject: successful update
  | 2018-03-07 22:57:00 INFO  KafkaClusterOperations:436 - Updating Kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:150 - update kafka cluster my-cluster-kafka in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:160 - kafka cluster my-cluster-kafka in namespace myproject: successful update
  | 2018-03-07 22:57:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:57:00 INFO  KafkaClusterOperations:665 - Updating Topic Controller my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:150 - update topic-controller cluster my-cluster-topic-controller in namespace myproject
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:160 - topic-controller cluster my-cluster-topic-controller in namespace myproject: successful update
  | 2018-03-07 22:57:00 INFO  AbstractClusterOperations:255 - Kafka cluster updated my-cluster
```

**Comment by tombentley** [comment]
This should now be fixed.
